import { Router } from "express";
import academicSessionRoutes from "./academicSession.routes.js";
import admissionRoutes from "./admission.routes.js";
import assignmentRoutes from "./assignment.routes.js";
import attendanceRoutes from "./attendance.routes.js";
import authRoutes from "./auth.routes.js";
import batchRoutes from "./batch.routes.js";
import bookRoutes from "./book.routes.js";
import campusRoutes from "./campus.routes.js";
import courseOfferingRoutes from "./courseOffering.routes.js";
import dashboardRoutes from "./dashboard.routes.js";
import departmentRoutes from "./department.routes.js";
import eventRoutes from "./event.routes.js";
import examRoutes from "./exam.routes.js";
import facultyRoutes from "./faculty.routes.js";
import feeRoutes from "./fee.routes.js";
import feeStructureRoutes from "./feeStructure.routes.js";
import financeRoutes from "./finance.routes.js";
import hrRoutes from "./hr.routes.js";
import notificationRoutes from "./notification.routes.js";
import programRoutes from "./program.routes.js";
import subjectRoutes from "./subject.routes.js";
import reportRoutes from "./report.routes.js";
import semesterRoutes from "./semester.routes.js";
import settingsRoutes from "./settings.routes.js";
import studentRoutes from "./student.routes.js";
import teacherRoutes from "./teacher.routes.js";
import transportRoutes from "./transport.routes.js";
import universityRoutes from "./university.routes.js";

const router = Router();

router.use("/students", studentRoutes);
router.use("/teachers", teacherRoutes);
router.use("/departments", departmentRoutes);
router.use("/offerings", courseOfferingRoutes);
router.use("/programs", programRoutes);
router.use("/subjects", subjectRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/admissions", admissionRoutes);
router.use("/assignments", assignmentRoutes);
router.use("/exams", examRoutes);
router.use("/faculties", facultyRoutes);
router.use("/books", bookRoutes);
router.use("/transport", transportRoutes);
router.use("/events", eventRoutes);
router.use("/fees", feeRoutes);
router.use("/fee-structures", feeStructureRoutes);
router.use("/finance", financeRoutes);
router.use("/hr", hrRoutes);
router.use("/reports", reportRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/notifications", notificationRoutes);
router.use("/settings", settingsRoutes);
router.use("/auth", authRoutes);
router.use("/academic-sessions", academicSessionRoutes);
router.use("/semesters", semesterRoutes);
router.use("/batches", batchRoutes);
router.use("/universities", universityRoutes);
router.use("/campuses", campusRoutes);

export default router;