export const SEED_STRUCTURE = {
  university: {
    universityName: 'University Management Demo',
    universityCode: 'UMS',
    shortName: 'UMS',
    universityType: 'Private',
    officialEmail: 'info@ums-demo.edu.pk',
    phoneNumber: '+92-300-0000000',
    website: 'https://ums-demo.edu.pk',
    country: 'Pakistan',
    province: 'Punjab',
    city: 'Lahore',
    address: 'Main Boulevard',
  },
  campuses: [
    {
      name: 'Main Campus',
      campusCode: 'MAIN',
      type: 'Main Campus',
      isMainCampus: true,
      phone: '+92-42-1111111',
      email: 'main@ums-demo.edu.pk',
      description: 'Primary campus for computing and engineering',
    },
    {
      name: 'City Campus',
      campusCode: 'CITY',
      type: 'Branch',
      isMainCampus: false,
      phone: '+92-42-2222222',
      email: 'city@ums-demo.edu.pk',
      description: 'Downtown campus for business and arts',
    },
  ],
  faculties: [
    {
      code: 'FOC',
      name: 'Faculty of Computing',
      campusCodes: ['MAIN', 'CITY'],
      departments: [
        { code: 'CS', name: 'Computer Science', programs: ['BSCS'], campusCodes: ['MAIN'] },
        { code: 'SE', name: 'Software Engineering', programs: ['BSSE'], campusCodes: ['MAIN'] },
        { code: 'IT', name: 'Information Technology', programs: ['BSIT'], campusCodes: ['MAIN', 'CITY'] },
      ],
    },
    {
      code: 'FOE',
      name: 'Faculty of Engineering',
      campusCodes: ['MAIN'],
      departments: [
        { code: 'EE', name: 'Electrical Engineering', programs: ['BSEE'], campusCodes: ['MAIN'] },
      ],
    },
    {
      code: 'FOB',
      name: 'Faculty of Business',
      campusCodes: ['CITY'],
      departments: [
        { code: 'BA', name: 'Business Administration', programs: ['BBA'], campusCodes: ['CITY'] },
        { code: 'AC', name: 'Accounting & Finance', programs: ['BSAF'], campusCodes: ['CITY'] },
        { code: 'MG', name: 'Management Sciences', programs: ['BSMS'], campusCodes: ['CITY', 'MAIN'] },
      ],
    },
    {
      code: 'FOA',
      name: 'Faculty of Arts & Social Sciences',
      campusCodes: ['CITY', 'MAIN'],
      departments: [
        { code: 'EN', name: 'English', programs: ['BA-ENG'], campusCodes: ['CITY'] },
        { code: 'PS', name: 'Political Science', programs: ['BA-PS'], campusCodes: ['MAIN'] },
      ],
    },
  ],
  programMeta: {
    // admissionFee = one-time seat fee (NOT part of semester tuition packages)
    BSCS: {
      name: 'Bachelor of Computer Science',
      degreeLevel: 'BS',
      duration: 8,
      totalCredits: 120,
      admissionFee: 25000,
      admissionOpensAt: '2026-01-01',
      admissionClosesAt: '2026-12-31',
    },
    BSSE: {
      name: 'Bachelor of Software Engineering',
      degreeLevel: 'BS',
      duration: 8,
      totalCredits: 120,
      admissionFee: 25000,
      admissionOpensAt: '2026-01-01',
      admissionClosesAt: '2026-12-31',
    },
    BSIT: {
      name: 'Bachelor of Information Technology',
      degreeLevel: 'BS',
      duration: 8,
      totalCredits: 120,
      admissionFee: 20000,
      admissionOpensAt: '2026-01-01',
      admissionClosesAt: '2026-06-30',
    },
    BSEE: {
      name: 'Bachelor of Electrical Engineering',
      degreeLevel: 'BS',
      duration: 8,
      totalCredits: 120,
      admissionFee: 30000,
      // No window — Active but closed for public apply until staff sets dates
    },
    BBA: {
      name: 'Bachelor of Business Administration',
      degreeLevel: 'BBA',
      duration: 8,
      totalCredits: 120,
      admissionFee: 15000,
      admissionOpensAt: '2026-01-01',
      admissionClosesAt: '2026-12-31',
    },
    BSAF: {
      name: 'Bachelor of Accounting & Finance',
      degreeLevel: 'BS',
      duration: 8,
      totalCredits: 120,
      admissionFee: 15000,
      admissionOpensAt: '2025-01-01',
      admissionClosesAt: '2025-06-30',
    },
    BSMS: {
      name: 'Bachelor of Management Sciences',
      degreeLevel: 'BS',
      duration: 8,
      totalCredits: 120,
      admissionFee: 15000,
      admissionOpensAt: '2026-01-01',
      admissionClosesAt: '2026-12-31',
    },
    'BA-ENG': {
      name: 'Bachelor of Arts in English',
      degreeLevel: 'Other',
      duration: 8,
      totalCredits: 120,
      admissionFee: 10000,
    },
    'BA-PS': {
      name: 'Bachelor of Arts in Political Science',
      degreeLevel: 'Other',
      duration: 8,
      totalCredits: 120,
      admissionFee: 10000,
    },
  },
  feeEffectiveFrom: '2024-01-01',
  feeSeedReason: 'Academic structure seed — semester tuition only; admissionFee is separate on Program',
};
