/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAcademicSessionsRouteImport } from './routes/app.academic-sessions'
import { Route as AppAdmissionsRouteImport } from './routes/app.admissions'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppAssignmentsRouteImport } from './routes/app.assignments'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppBatchesRouteImport } from './routes/app.batches'
import { Route as AppCampusesRouteImport } from './routes/app.campuses'
import { Route as AppCoursesRouteImport } from './routes/app.courses'
import { Route as AppDepartmentsRouteImport } from './routes/app.departments'
import { Route as AppEventsRouteImport } from './routes/app.events'
import { Route as AppExamsRouteImport } from './routes/app.exams'
import { Route as AppFeesRouteImport } from './routes/app.fees'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppHostelRouteImport } from './routes/app.hostel'
import { Route as AppHrRouteImport } from './routes/app.hr'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppOnlineClassesRouteImport } from './routes/app.online-classes'
import { Route as AppQrRouteImport } from './routes/app.qr'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSemestersRouteImport } from './routes/app.semesters'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppTeachersRouteImport } from './routes/app.teachers'
import { Route as AppTransportRouteImport } from './routes/app.transport'
import { Route as AppUniversityRouteImport } from './routes/app.university'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicSessionsRoute = AppAcademicSessionsRouteImport.update({
  id: '/academic-sessions',
  path: '/academic-sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppAdmissionsRoute = AppAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesRoute = AppBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AppRoute,
} as any)
const AppCampusesRoute = AppCampusesRouteImport.update({
  id: '/campuses',
  path: '/campuses',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsRoute = AppExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppHostelRoute = AppHostelRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppOnlineClassesRoute = AppOnlineClassesRouteImport.update({
  id: '/online-classes',
  path: '/online-classes',
  getParentRoute: () => AppRoute,
} as any)
const AppQrRoute = AppQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSemestersRoute = AppSemestersRouteImport.update({
  id: '/semesters',
  path: '/semesters',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppTransportRoute = AppTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AppRoute,
} as any)
const AppUniversityRoute = AppUniversityRouteImport.update({
  id: '/university',
  path: '/university',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/app/academic-sessions': typeof AppAcademicSessionsRoute
  '/app/admissions': typeof AppAdmissionsRoute
  '/app/ai': typeof AppAiRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/batches': typeof AppBatchesRoute
  '/app/campuses': typeof AppCampusesRoute
  '/app/courses': typeof AppCoursesRoute
  '/app/departments': typeof AppDepartmentsRoute
  '/app/events': typeof AppEventsRoute
  '/app/exams': typeof AppExamsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/hostel': typeof AppHostelRoute
  '/app/hr': typeof AppHrRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/online-classes': typeof AppOnlineClassesRoute
  '/app/qr': typeof AppQrRoute
  '/app/reports': typeof AppReportsRoute
  '/app/semesters': typeof AppSemestersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/transport': typeof AppTransportRoute
  '/app/university': typeof AppUniversityRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/app/academic-sessions': typeof AppAcademicSessionsRoute
  '/app/admissions': typeof AppAdmissionsRoute
  '/app/ai': typeof AppAiRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/batches': typeof AppBatchesRoute
  '/app/campuses': typeof AppCampusesRoute
  '/app/courses': typeof AppCoursesRoute
  '/app/departments': typeof AppDepartmentsRoute
  '/app/events': typeof AppEventsRoute
  '/app/exams': typeof AppExamsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/hostel': typeof AppHostelRoute
  '/app/hr': typeof AppHrRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/online-classes': typeof AppOnlineClassesRoute
  '/app/qr': typeof AppQrRoute
  '/app/reports': typeof AppReportsRoute
  '/app/semesters': typeof AppSemestersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/transport': typeof AppTransportRoute
  '/app/university': typeof AppUniversityRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/app/academic-sessions': typeof AppAcademicSessionsRoute
  '/app/admissions': typeof AppAdmissionsRoute
  '/app/ai': typeof AppAiRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/batches': typeof AppBatchesRoute
  '/app/campuses': typeof AppCampusesRoute
  '/app/courses': typeof AppCoursesRoute
  '/app/departments': typeof AppDepartmentsRoute
  '/app/events': typeof AppEventsRoute
  '/app/exams': typeof AppExamsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/hostel': typeof AppHostelRoute
  '/app/hr': typeof AppHrRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/online-classes': typeof AppOnlineClassesRoute
  '/app/qr': typeof AppQrRoute
  '/app/reports': typeof AppReportsRoute
  '/app/semesters': typeof AppSemestersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/transport': typeof AppTransportRoute
  '/app/university': typeof AppUniversityRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/app/academic-sessions'
    | '/app/admissions'
    | '/app/ai'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/batches'
    | '/app/campuses'
    | '/app/courses'
    | '/app/departments'
    | '/app/events'
    | '/app/exams'
    | '/app/fees'
    | '/app/finance'
    | '/app/hostel'
    | '/app/hr'
    | '/app/library'
    | '/app/notifications'
    | '/app/online-classes'
    | '/app/qr'
    | '/app/reports'
    | '/app/semesters'
    | '/app/settings'
    | '/app/students'
    | '/app/teachers'
    | '/app/transport'
    | '/app/university'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/app/academic-sessions'
    | '/app/admissions'
    | '/app/ai'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/batches'
    | '/app/campuses'
    | '/app/courses'
    | '/app/departments'
    | '/app/events'
    | '/app/exams'
    | '/app/fees'
    | '/app/finance'
    | '/app/hostel'
    | '/app/hr'
    | '/app/library'
    | '/app/notifications'
    | '/app/online-classes'
    | '/app/qr'
    | '/app/reports'
    | '/app/semesters'
    | '/app/settings'
    | '/app/students'
    | '/app/teachers'
    | '/app/transport'
    | '/app/university'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/app/academic-sessions'
    | '/app/admissions'
    | '/app/ai'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/batches'
    | '/app/campuses'
    | '/app/courses'
    | '/app/departments'
    | '/app/events'
    | '/app/exams'
    | '/app/fees'
    | '/app/finance'
    | '/app/hostel'
    | '/app/hr'
    | '/app/library'
    | '/app/notifications'
    | '/app/online-classes'
    | '/app/qr'
    | '/app/reports'
    | '/app/semesters'
    | '/app/settings'
    | '/app/students'
    | '/app/teachers'
    | '/app/transport'
    | '/app/university'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/academic-sessions': {
      id: '/app/academic-sessions'
      path: '/academic-sessions'
      fullPath: '/app/academic-sessions'
      preLoaderRoute: typeof AppAcademicSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admissions': {
      id: '/app/admissions'
      path: '/admissions'
      fullPath: '/app/admissions'
      preLoaderRoute: typeof AppAdmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assignments': {
      id: '/app/assignments'
      path: '/assignments'
      fullPath: '/app/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batches': {
      id: '/app/batches'
      path: '/batches'
      fullPath: '/app/batches'
      preLoaderRoute: typeof AppBatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campuses': {
      id: '/app/campuses'
      path: '/campuses'
      fullPath: '/app/campuses'
      preLoaderRoute: typeof AppCampusesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses': {
      id: '/app/courses'
      path: '/courses'
      fullPath: '/app/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/departments': {
      id: '/app/departments'
      path: '/departments'
      fullPath: '/app/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exams': {
      id: '/app/exams'
      path: '/exams'
      fullPath: '/app/exams'
      preLoaderRoute: typeof AppExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fees': {
      id: '/app/fees'
      path: '/fees'
      fullPath: '/app/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hostel': {
      id: '/app/hostel'
      path: '/hostel'
      fullPath: '/app/hostel'
      preLoaderRoute: typeof AppHostelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hr': {
      id: '/app/hr'
      path: '/hr'
      fullPath: '/app/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/online-classes': {
      id: '/app/online-classes'
      path: '/online-classes'
      fullPath: '/app/online-classes'
      preLoaderRoute: typeof AppOnlineClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/qr': {
      id: '/app/qr'
      path: '/qr'
      fullPath: '/app/qr'
      preLoaderRoute: typeof AppQrRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/semesters': {
      id: '/app/semesters'
      path: '/semesters'
      fullPath: '/app/semesters'
      preLoaderRoute: typeof AppSemestersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teachers': {
      id: '/app/teachers'
      path: '/teachers'
      fullPath: '/app/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transport': {
      id: '/app/transport'
      path: '/transport'
      fullPath: '/app/transport'
      preLoaderRoute: typeof AppTransportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/university': {
      id: '/app/university'
      path: '/university'
      fullPath: '/app/university'
      preLoaderRoute: typeof AppUniversityRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAcademicSessionsRoute: typeof AppAcademicSessionsRoute
  AppAdmissionsRoute: typeof AppAdmissionsRoute
  AppAiRoute: typeof AppAiRoute
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBatchesRoute: typeof AppBatchesRoute
  AppCampusesRoute: typeof AppCampusesRoute
  AppCoursesRoute: typeof AppCoursesRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppEventsRoute: typeof AppEventsRoute
  AppExamsRoute: typeof AppExamsRoute
  AppFeesRoute: typeof AppFeesRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppHostelRoute: typeof AppHostelRoute
  AppHrRoute: typeof AppHrRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOnlineClassesRoute: typeof AppOnlineClassesRoute
  AppQrRoute: typeof AppQrRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSemestersRoute: typeof AppSemestersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppTeachersRoute: typeof AppTeachersRoute
  AppTransportRoute: typeof AppTransportRoute
  AppUniversityRoute: typeof AppUniversityRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademicSessionsRoute: AppAcademicSessionsRoute,
  AppAdmissionsRoute: AppAdmissionsRoute,
  AppAiRoute: AppAiRoute,
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppBatchesRoute: AppBatchesRoute,
  AppCampusesRoute: AppCampusesRoute,
  AppCoursesRoute: AppCoursesRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppEventsRoute: AppEventsRoute,
  AppExamsRoute: AppExamsRoute,
  AppFeesRoute: AppFeesRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppHostelRoute: AppHostelRoute,
  AppHrRoute: AppHrRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOnlineClassesRoute: AppOnlineClassesRoute,
  AppQrRoute: AppQrRoute,
  AppReportsRoute: AppReportsRoute,
  AppSemestersRoute: AppSemestersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppTeachersRoute: AppTeachersRoute,
  AppTransportRoute: AppTransportRoute,
  AppUniversityRoute: AppUniversityRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
